apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: kf-kcc-0415-admin@PROJECT.iam.gserviceaccount.com # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"kf-kcc-0415-001"},{"name":"gcloud.core.project","value":"PROJECT"}]}}
