apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: kserve/kserve-controller-manager
  name: kserve-controller-manager
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
