apiVersion: apps/v1
kind: StatefulSet
metadata: # kpt-merge: kserve/kserve-controller-manager
  name: kserve-controller-manager
  namespace: kserve
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
