apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: kserve/kserve-models-web-app
  name: kserve-models-web-app
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
