---
# Source: flink-operator/templates/flink-operator.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-operator-manager-role
subjects:
- kind: ServiceAccount
  name: flink-operator-sa
  namespace: kubeflow
---
# Source: flink-operator/templates/flink-operator.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: flink-operator-sa
  namespace: kubeflow
