---
# Source: flink-operator/templates/flink-operator.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-operator-leader-election-role
  namespace: kubeflow
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch

