apiVersion: v1
kind: ServiceAccount
metadata:
  # name: profiles-controller-service-account
  # It should have profiles- prefix, but because the profile upstream has added this prefix, it will cause 
  # unique ID not found issue if we specify profiles- in patch.
  name: controller-service-account
  annotations:
    iam.gke.io/gcp-service-account: KUBEFLOW-NAME-admin@PROJECT.iam.gserviceaccount.com # {"$kpt-set":"admin-sa-ref"}
