apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- iap-ingress-config.yaml
- service-accounts.yaml
resources:
- ../../../../packages/iap-ingress/v3 # {"$kpt-set":"gcp-iap-ingress-v3"}
# - ../../../../packages/iap-gateway/base # {"$kpt-set":"istio-iap-gateway-base"}
