apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-ui
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: katib-ui
        env:
        - name: USERID_HEADER
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-header
        - name: USERID_PREFIX
          value: null
          valueFrom:
            configMapKeyRef:
              name: kubeflow-config
              key: userid-prefix
