apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
# Labels to add to all resources and selectors.
commonLabels:
  app: kserve
  app.kubernetes.io/name: kserve
resources:
- models-web-app
- kserve/upstream/kserve_kubeflow.yaml
- kserve/upstream/kserve-runtimes.yaml
patchesStrategicMerge:
- patches/deployment.yaml
- patches/web-app-sidecar.yaml
- web-app-authorization-policy.yaml
patchesJson6902:
- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: serving-cert
    namespace: kubeflow
  path: patches/webhook-certificate.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
- kserve-params.yaml