# Define the Google Service Account to be used with CNRM
# in the management cluster.
# Also define the workload identity binding.
#
# These resources should be created with AnthosCLI since we
# need to bootstrap the management cluster.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: MANAGED-GSA-NAME # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_gsa_name","value":"MANAGED-GSA-NAME"}]}}
  namespace: "MANAGED_PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"managed_project","value":"MANAGED_PROJECT"}}}
spec:
  displayName: Service account for CNRM
---
# TODO(jlewi): Switch to IAMPolicyMember once anthos CLI supports that.
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: cnrm-system-MANAGED_PROJECT-wi # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"MANAGED_PROJECT"}]}}
  namespace: "MANAGED_PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"managed_project","value":"MANAGED_PROJECT"}}}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1alpha1
    kind: IAMServiceAccount
    name: MANAGED-GSA-NAME # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_gsa_name","value":"MANAGED-GSA-NAME"}]}}
  bindings:
  - role: roles/iam.workloadIdentityUser
    members:
    # We use a partial setter for the entire workload id pool; i.e. ${PROJECT}.svc.id.goog
    # Because in the case where the managed project and host project are the same setters
    # for host and managed project would be the same and kpt would no longer know which field goes  where.
    - serviceAccount:HOST_PROJECT.svc.id.goog[cnrm-system/cnrm-controller-manager-MANAGED_PROJECT] # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"host_id_pool","value":"HOST_PROJECT.svc.id.goog"},{"name":"managed_project","value":"MANAGED_PROJECT"}]}}
---
# Make the GCP SA a project owner
# TODO(jlewi): AnthosCLI doesn't appear to support IAMPolicy Member yet so 
# as a work around you will need to use gcloud

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: cnrm-system-MANAGED_PROJECT-owner # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"MANAGED_PROJECT"}]}}
  namespace: "MANAGED_PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","setter":{"name":"managed_project","value":"MANAGED_PROJECT"}}}
spec:
  member: serviceAccount:MANAGED-GSA-NAME@MANAGED_PROJECT.iam.gserviceaccount.com # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"MANAGED_PROJECT"},{"name":"managed_gsa_name","value":"MANAGED-GSA-NAME"}]}}
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/MANAGED_PROJECT # {"type":"string","x-kustomize":{"partialSetters":[{"name":"managed_project","value":"MANAGED_PROJECT"}]}}
