# The purpose of this file is to store values in setters
# so its easy to get them using yq for use in Make.
# TODO(jlewi): File a feature request to have kpt list-setters return the value
project: HOST_PROJECT # {"$kpt-set":"gcloud.core.project"}
name: YOUR-NAME # {"$kpt-set":"name"}
location: us-central1 # {"$kpt-set":"location"}
