# AnthosCLI requires a nodepool object to describe the nodepool.
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: MANAGEMENT-NAME-pool # {"$kpt-set":"pool"}
spec:
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    machineType: n1-standard-4
    preemptible: false
    oauthScopes:
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/trace.append
    metadata:
      disable-legacy-endpoints: "true"
    workloadMetadataConfig:
      mode: GKE_METADATA
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: MANAGEMENT-NAME # {"$kpt-set":"name"}
