# Define a transform to remove namespace from cluster scoped resources
apiVersion: v1alpha1 
kind: RemoveNamespace
metadata:
  name: remove-namespace
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kubeflow-images-public/kpt-fns:v1.1-rc.0-22-gbb803bc@sha256:23c586b7df3603bcf6610e8089acfe03956473cd4d367bbc05270bba74dc29fd
spec:
  clusterKinds:
  - kind: Profile
    group: kubeflow.org
  - kind: ClusterIssuer
    group: cert-manager.io
  - kind: CompositeController
    group: metacontroller.k8s.io
  - kind: ClusterRbacConfig
    group: rbac.istio.io
 