apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: KUBEFLOW-NAME-admin-workload-identity-user # kpt-set: ${name}-admin-workload-identity-user
spec:
  member: serviceAccount:PROJECT.svc.id.goog[kubeflow/profiles-controller-service-account] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[kubeflow/profiles-controller-service-account]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: KUBEFLOW-NAME-admin # kpt-set: ${name}-admin
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: KUBEFLOW-NAME-admin-kubeflow-wi # kpt-set: ${name}-admin-kubeflow-wi
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: KUBEFLOW-NAME-admin # kpt-set: ${name}-admin
  member: serviceAccount:PROJECT.svc.id.goog[kubeflow/kf-admin] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[kubeflow/kf-admin]
  role: roles/iam.workloadIdentityUser
---
# kf-admin binding in namespace istio-system
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: KUBEFLOW-NAME-admin-istio-wi # kpt-set: ${name}-admin-istio-wi
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: KUBEFLOW-NAME-admin # kpt-set: ${name}-admin
  member: serviceAccount:PROJECT.svc.id.goog[istio-system/kf-admin] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[istio-system/kf-admin]
  role: roles/iam.workloadIdentityUser
