apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./knative-0-22-0/serving-core.yaml
- ./knative-0-22-0/net-istio.yaml
namespace: knative-serving
commonLabels:
  kustomize.component: knative
  app.kubernetes.io/component: knative-serving-install
  app.kubernetes.io/name: knative-serving-install
patches:
- path: patches/namespace-patch.yaml
