apiVersion: v1
data:
  admin: EMAIL # {"$kpt-set":"email"}
  gcp-sa: KUBEFLOW-NAME-user@PROJECT.iam.gserviceaccount.com # {"$kpt-set":"gcp-sa"}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: profiles-config
