apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    gke.io/cluster: "bootstrap://"
  name: default-pool
  namespace: "PROJECT" # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.core.project"}
spec:
  initialNodeCount: 2
  autoscaling:
    minNodeCount: 2
    maxNodeCount: 4 # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.container.nodepool.max-nodes"}
  nodeConfig:
    machineType: e2-standard-4
    workloadMetadataConfig:
      nodeMetadata: GKE_METADATA_SERVER
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: "asm-cluster" # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.container.cluster"}
