apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: ${name}-admin@${gcloud.core.project}.iam.gserviceaccount.com # kpt-set: ${name}-admin@${gcloud.core.project}.iam.gserviceaccount.com
