apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "api-approved.kubernetes.io": "unapproved, request not yet submitted"
  name: cloudendpoints.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  names:
    kind: CloudEndpoint
    plural: cloudendpoints
    shortNames:
    - cloudep
    - ce
    singular: cloudendpoint
  scope: Namespaced
  versions: 
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                project: 
                  type: string
                targetIngress:
                  properties:
                    name:
                      type: string
                    namespace: 
                      type: string
                  type: object
                  required:
                  - name
                  - namespace
              required:
              - project
              - targetIngress
              type: object
            status:
              type: object
          required:
          - metadata
          - spec
          type: object
