apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata
  name: metadata-grpc-service
  namespace: kubeflow
spec:
  ports:
  - name: grpc-api
    port: 8080
    protocol: TCP
  selector:
    component: metadata-grpc-server
  type: ClusterIP
