apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata-envoy
  name: metadata-envoy-service
  namespace: kubeflow
spec:
  ports:
  - name: md-envoy
    port: 9090
    protocol: TCP
  selector:
    component: metadata-envoy
  type: ClusterIP
