# GKE
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: gke
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: container.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: compute
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: compute.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: monitoring
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: monitoring.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: logging
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: logging.googleapis.com

# TODO(jlewi): Does order matter?
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: meshca
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: meshca.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: meshtelemetry
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: meshtelemetry.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: mesh
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: meshconfig.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: iamcredentials
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: iamcredentials.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: anthos
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: anthos.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: gkeconnect
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: gkeconnect.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: gkehub
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: gkehub.googleapis.com
---
apiVersion: cnrm.cloud.google.com/v1alpha1
kind: CloudService
metadata:
  name: resourcemanager
  namespace: "PROJECT" # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"gcloud.core.project","value":"PROJECT"}]}}
spec:
  service: cloudresourcemanager.googleapis.com
