apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    pilot:
      k8s:
        env:
        - name: SPIFFE_BUNDLE_ENDPOINTS
          value: ""
        - name: TOKEN_AUDIENCES
          value: "istio-ca,PROJECT.svc.id.goog" # {"$ref":"#/definitions/io.k8s.cli.substitutions.token-audiences"}
        - name: ENABLE_STACKDRIVER_MONITORING
          value: "true" # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.controlplane.monitoring.enabled"}
  meshConfig:
    trustDomain: "cluster.local"
    defaultConfig:
      proxyMetadata:
        CA_PROVIDER: "Citadel"
        PLUGINS: ""
  values:
    global:
      caAddress: ""
      pilotCertProvider: "istiod"
