apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- workload-identity-bindings-patch.yaml
configMapGenerator:
- envs:
  - params.env
  name: kubeflow-config
generatorOptions:
  disableNameSuffixHash: true
vars:
# We need to define vars at the top level otherwise we will get
# conflicts. 
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
# - fieldref:
#     fieldpath: metadata.namespace
#   name: katib-ui-namespace
#   objref:
#     kind: Service
#     name: katib-ui
#     apiVersion: v1
