# Define the self-signed issuer for Kubeflow
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- ../cert-manager/cert-manager-1-3/cert-manager/kubeflow-issuer
