apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../upstream/manifests/common/cert-manager/cert-manager/overlays/application # {"$kpt-set":"cert-manager-cert-manager-v3"}
