apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./upstream/knative-serving-crds/base
- ./upstream/knative-serving-install/base
- ../istio/istio-1-9-0/cluster-local-gateway/base